version: '3.8'

services:
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
      target: prod
    env_file:
      - cargo.env

  proxy:
  build: proxy
  ports:
    - 8080:80
  depends_on:
    - backend