version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: development

  proxy:
  build: proxy
  ports:
    - 8080:80
  depends_on:
    - backend